version: '3.8'

services:

  # =========================
  # UPSTREAM NODES
  # =========================

  msc-generator:
    build:
      context: ./generator
    container_name: msc-generator
    command: ["configs/msc.conf"]
    volumes:
      - ./Up-Stream-Nodes/msc-node/cdr-files:/data/msc-node/cdr-files
    restart: unless-stopped

  pgw-generator:
    build:
      context: ./generator
    container_name: pgw-generator
    command: ["configs/pgw.conf"]
    volumes:
      - ./Up-Stream-Nodes/pgw-node/cdr-files:/data/pgw-node/cdr-files
    restart: unless-stopped

  smsc-generator:
    build:
      context: ./generator
    container_name: smsc-generator
    command: ["configs/smsc.conf"]
    volumes:
      - ./Up-Stream-Nodes/smsc-node/cdr-files:/data/smsc-node/cdr-files
    restart: unless-stopped

  # =========================
  # DOWNSTREAM NODES
  # =========================

  billing-watcher:
    build:
      context: ./Down-Stream-Nodes
    container_name: billing-watcher
    command: ["configs/billing.conf"]
    volumes:
      - ./Down-Stream-Nodes/billing-node/cdr-files:/data/billing-node/cdr-files
    restart: unless-stopped

  charging-watcher:
    build:
      context: ./Down-Stream-Nodes
    container_name: charging-watcher
    command: ["configs/charging.conf"]
    volumes:
      - ./Down-Stream-Nodes/charging-node/cdr-files:/data/charging-node/cdr-files
    restart: unless-stopped

  fraud-watcher:
    build:
      context: ./Down-Stream-Nodes
    container_name: fraud-watcher
    command: ["configs/fraud.conf"]
    volumes:
      - ./Down-Stream-Nodes/fraud-node/cdr-files:/data/fraud-node/cdr-files
    restart: unless-stopped